db2 connect to xip;
db2 "export to XIP_CHNLASSTINFO.txt of del select * from XIP_CHNLASSTINFO";
db2 "export to XIP_CHNLCOMMPARM.txt of del select * from XIP_CHNLCOMMPARM";
db2 "export to XIP_CHNLINFO.txt of del select * from XIP_CHNLINFO";
db2 "export to XIP_CHNLKEYINFO.txt of del select * from XIP_CHNLKEYINFO";
db2 "export to XIP_CHNLROUTE.txt of del select * from XIP_CHNLROUTE";
db2 "export to XIP_FIXEDCONV.txt of del select * from XIP_FIXEDCONV";
db2 "export to XIP_FTPEXECSEQU.txt of del select * from XIP_FTPEXECSEQU";
db2 "export to XIP_FTPPARM.txt of del select * from XIP_FTPPARM";
db2 "export to XIP_PKGINFO.txt of del select * from XIP_PKGINFO";
db2 "export to XIP_SERVICEFLOW.txt of del select * from XIP_SERVICEFLOW";
db2 "export to XIP_TAGATTR.txt of del select * from XIP_TAGATTR";
db2 "export to XIP_TAGCONV.txt of del select * from XIP_TAGCONV";
db2 "export to XIP_TRADEFLOW.txt of del select * from XIP_TRADEFLOW";
db2 "export to XIP_TRADEINFO.txt of del select * from XIP_TRADEINFO";
db2 "export to XIP_TRADFUNCIO.txt of del select * from XIP_TRADFUNCIO";
db2 "export to XIP_XML2CONV.txt of del select * from XIP_XML2CONV";
db2 "export to XIP_XMLCONV.txt of del select * from XIP_XMLCONV";
db2 "export to XIP_XMLNODEATTR.txt of del select * from XIP_XMLNODEATTR";
db2 "export to XIP_XMLPKGINFO.txt of del select * from XIP_XMLPKGINFO";
db2 "export to XIP_8583CONV.txt of del select * from XIP_8583CONV";
db2 "export to XIP_8583DIC.txt of del select * from XIP_8583DIC";
db2 "export to XIP_TRADEBITMAP.txt of del select * from XIP_TRADEBITMAP";
db2 connect reset;
