db2 "connect to xip";
db2 "import from TIPS_CHKLIST.txt of del insert into TIPS_CHKLIST";
db2 "import from AGENT_BOOK.txt of del insert into AGENT_BOOK";
db2 "import from BCP_TRACELOG.txt.txt of del insert into BCP_TRACELOG";
db2 "import from BEPS_SNDLIST.txt of del insert into BEPS_SNDLIST";
db2 "import from BUS_ORGICINFO.txt of del insert into BUS_ORGICINFO";
db2 "import from BUS_TRADRCD.txt of del insert into BUS_TRADRCD";
db2 "import from CC_TRCLOG.txt of del insert into CC_TRCLOG";
db2 "import from CU_CU_RCD.txt of del insert into CU_CU_RCD";
db2 "import from CU_ERR_ISSUE.txt of del insert into CU_ERR_ISSUE";
db2 "import from CU_TX_RCD.txt of del insert into CU_TX_RCD";
db2 "import from HELIC_MKCARDELE.txt of del insert into HELIC_MKCARDELE";
db2 "import from HVPS_RCVLIST.txt of del insert into HVPS_RCVLIST";
db2 "import from HVPS_SNDADDINF.txt of del insert into HVPS_SNDADDINF";
db2 "import from HVPS_SNDLIST.txt of del insert into HVPS_SNDLIST";
db2 "import from IBPS_ACCTINFO.txt of del insert into IBPS_ACCTINFO";
db2 "import from IBPS_HOSTDATA.txt of del insert into IBPS_HOSTDATA";
db2 "import from IBPS_NETTMSGLOG.txt of del insert into IBPS_NETTMSGLOG";
db2 "import from ID_CHK_SIN.txt of del insert into ID_CHK_SIN";
db2 "import from INT_SYS_BIND.txt of del insert into INT_SYS_BIND";
db2 "import from LNTRA_TRCLOG.txt of del insert into LNTRA_TRCLOG";
db2 "import from MEDIINS_TRCLOG.txt of del insert into MEDIINS_TRCLOG";
db2 "import from MOBI_TRCLOG.txt of del insert into MOBI_TRCLOG";
db2 "import from NETPLAT_TRACELOG.txt of del insert NETPLAT_TRACELOG";
db2 "import from NT_DEMLETTER_COL.txt of del insert into NT_DEMLETTER_COL";
db2 "import from PMTS_OTHACC.txt of del insert into PMTS_OTHACC";
db2 "import from POWER_TAIL.txt of del insert into POWER_TAIL;
db2 "import from POWER_TRCLOG.txt of del insert into POWER_TRCLOG";
db2 "import from PW_TRCLOG.txt of del insert into PW_TRCLOG";
db2 "import from SAPS_LIQRTNLIST.txt of del insert into SAPS_LIQRTNLIST";
db2 "import from SS_TRCLOG.txt of del insert into SS_TRCLOG";
db2 "import from TOBACTRALOG.txt of del insert into TOBACTRALOG";
db2 "import from TIPS_TAXTYPELST.txt of del insert into TIPS_TAXTYPELST";
db2 "import from UNI_TRCLOG.txt of del insert into UNI_TRCLOG";
db2 "import from WT_TRCLOG.txt of del insert into WT_TRCLOG";
db2 "import from YXPT_TXLOG.txt of del insert into YXPT_TXLOG";
db2 "connect reset";

